# PCCS TLS Secret Template
# Generate your own TLS certificate and key, then create this secret:
#
#   kubectl create secret tls pccs-tls-cert \
#     --cert=pccs-tls.crt \
#     --key=pccs-tls.key \
#     --namespace=default
#
# Or use cert-manager to auto-provision certificates.

apiVersion: v1
kind: Secret
metadata:
  name: pccs-tls-cert
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_CERTIFICATE>
  tls.key: <BASE64_ENCODED_PRIVATE_KEY>
