apiVersion: v1
kind: ConfigMap
metadata:
  name: sgx-attestation-conf
  namespace: default
data:
  sgx_default_qcnl.conf: |
    {
      "pccs_url": "https://pccs-service:8081/sgx/certification/v4/",
      "use_secure_cert": false,
      "collateral_service": "https://api.trustedservices.intel.com/sgx/certification/v4/",
      "tcb_update_type": "standard",
      "pccs_api_version": "3.1",
      "retry_times": 6,
      "retry_delay": 10,
      "pck_cache_expire_hours": 168,
      "verify_collateral_cache_expire_hours": 168,
      "local_cache_only": false
    }
  aesmd.conf: |
    #whitelisturl=https://whitelist-cf.trustedservices.intel.com/
    #cachedir=/tmp/aesmd/
    #proxytype=direct
    #pccs_url=https://pccs-service:8081/sgx/certification/v4/
    default quoting type = ecdsa_256